name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.0', '8.1', '8.2', '8.3' ]
        laravel-version: [ '9.*', '10.*', '11.*' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, pdo, pdo_sqlite, sqlite

      - name: Install dependencies
        run: |
          composer require "illuminate/database:${{ matrix.laravel-version }}" --with-all-dependencies --prefer-dist --no-interaction
          composer require "illuminate/support:${{ matrix.laravel-version }}" --with-all-dependencies --prefer-dist --no-interaction
          composer install --prefer-dist --no-interaction

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit
